const data ={
    products:[
        {
        name: "Nike slim T-shirt",
        slug: "nike-slim-shirt",
        category: "Shirts",
        image: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/70ebb896-f02e-40e1-99bd-382f0138cefb/pro-dri-fit-mens-slim-fit-short-sleeve-top-H7B5f3.png",
        price: 100,
        countInStock: 20,
        brand: "Nike",
        rating: 4.5,
        numReview: 10,
        desecription: "high quality product",
    },
    {
        name: "Jacket",
        slug: "H&M Jacket",
        category: "Jacket",
        image: "https://cdn.shopify.com/s/files/1/1364/2823/products/BUZZARD3_0fdce575-4cdf-47c3-a963-9731f04d6ad9_1080x.jpg?v=1602722180",
        price: 150,
        countInStock: 8,
        brand: "H&M",
        rating: 5,
        numReview: 15,
        desecription: "high quality product",
    },
    {
        name: "Adidas Fit Pant",
        slug: "Adidas Fit Pant",
        category: "Pants",
        image: "https://images.asos-media.com/products/adidas-originals-adicolor-three-stripe-skinny-joggers-in-black-black/14659230-1-black?$n_640w$&wid=513&fit=constrain",
        price: 75,
        countInStock: 7,
        brand: "Adidas",
        rating: 4.5,
        numReview: 15,
        desecription: "high quality product",
    },
    {
        name: "Jacket",
        slug: "H&MJacket",
        category: "Jacket",
        image: "https://img.mytheresa.com/1088/1088/66/jpeg/catalog/product/b9/P00702797.jpg",
        price: 120,
        countInStock: 17,
        brand: "H&M",
        rating: 4.5,
        numReview: 10,
        desecription: "high quality product",
    },
    {
        name: "Jacket",
        slug: "H&M-Jacket",
        category: "Jacket",
        image: "https://is4.revolveassets.com/images/p4/n/z/LCDE-WO170_V1.jpg",
        price: 200,
        countInStock: 12,
        brand: "H&M",
        rating: 4.5,
        numReview: 12,
        desecription: "high quality product",
    },
    {
        name: "Nike Training Dri-FIT",
        slug: "Nike Training Dri-FIT",
        category: "Shirts",
        image: "https://images.asos-media.com/products/nike-training-dri-fit-chest-swoosh-t-shirt-in-red/202972006-1-red?$n_750w$&wid=750&fit=constrain",
        price: 100,
        countInStock: 20,
        brand: "Nike",
        rating: 4.5,
        numReview: 10,
        desecription: "high quality product",
    },
    {
        name: "Puma Fit Pant",
        slug: "Puma Fit Pant",
        category: "Pants",
        image: "https://images.asos-media.com/products/puma-essentials-small-logo-joggers-in-khaki/204140419-1-khaki?$n_640w$&wid=513&fit=constrain",
        price: 75,
        countInStock: 7,
        brand: "Puma",
        rating: 4.5,
        numReview: 15,
        desecription: "high quality product",
    },
],
}

export default data ;